using Microsoft.AspNetCore.OpenApi;
using Microsoft.OpenApi;

namespace Pure.RelationalSchema.Storage.Abstractions.OpenAPI.Schema;

public sealed class StorageDataDocumentTransformer : IOpenApiDocumentTransformer
{
    // Maps schema component names (generated by ASP.NET Core OpenAPI) to schemas matching
    // the actual JSON serialization of Pure.RelationalSchema.Storage.Abstractions types.
    private static readonly IReadOnlyDictionary<string, OpenApiSchema> DataSchemas =
        new Dictionary<string, OpenApiSchema>(StringComparer.Ordinal)
        {
            // ICell serializes as: { "Value": "<string>" }
            ["ICell"] = new()
            {
                Type = JsonSchemaType.Object,
                Properties = new Dictionary<string, IOpenApiSchema>
                {
                    ["Value"] = new OpenApiSchema { Type = JsonSchemaType.String },
                },
            },
            // IRow serializes as: [{ "Column": {...}, "Cell": {...} }, ...]
            ["IRow"] = new()
            {
                Type = JsonSchemaType.Array,
                Items = new OpenApiSchema
                {
                    Type = JsonSchemaType.Object,
                    Properties = new Dictionary<string, IOpenApiSchema>
                    {
                        ["Column"] = new OpenApiSchemaReference("IColumn"),
                        ["Cell"] = new OpenApiSchemaReference("ICell"),
                    },
                },
            },
            // IStoredTableDataSet serializes as: { "TableSchema": {...}, "Rows": [...] }
            ["IStoredTableDataSet"] = new()
            {
                Type = JsonSchemaType.Object,
                Properties = new Dictionary<string, IOpenApiSchema>
                {
                    ["TableSchema"] = new OpenApiSchemaReference("ITable"),
                    ["Rows"] = new OpenApiSchema
                    {
                        Type = JsonSchemaType.Array,
                        Items = new OpenApiSchemaReference("IRow"),
                    },
                },
            },
            // IStoredSchemaDataSet serializes as: { "Schema": {...}, "Datasets": [...] }
            ["IStoredSchemaDataSet"] = new()
            {
                Type = JsonSchemaType.Object,
                Properties = new Dictionary<string, IOpenApiSchema>
                {
                    ["Schema"] = new OpenApiSchemaReference("ISchema"),
                    ["Datasets"] = new OpenApiSchema
                    {
                        Type = JsonSchemaType.Array,
                        Items = new OpenApiSchemaReference("IStoredTableDataSet"),
                    },
                },
            },
        };

    public Task TransformAsync(
        OpenApiDocument document,
        OpenApiDocumentTransformerContext context,
        CancellationToken cancellationToken
    )
    {
        if (document.Components?.Schemas is not { } schemas)
        {
            return Task.CompletedTask;
        }

        foreach ((string name, OpenApiSchema nativeSchema) in DataSchemas)
        {
            if (schemas.ContainsKey(name))
            {
                schemas[name] = nativeSchema;
            }
        }

        return Task.CompletedTask;
    }
}
